### ISSUE TITLE
Lights don't change color mode correctly when a scene is applied

### ISSUE THREAD

**Issue by quantumfrost** [tuya/tuya-home-assistant#695]
**Describe the bug**
If a light is in white mode, and the scene specifies a color, the light doesn't switch to color mode when the scene is activated.
If the light was already in color mode, it switches to the correct color when the scene is activated.

To reproduce:

1. Create new scene with the light. Choose a color, e.g. blue
2. Manually switch light to white mode from home assistant
3. Activate scene, nothing happens
4. Manually switch light to red from home assistant
5. Activate scene, now it correctly switches to blue

**Expected behavior**
The light should switch to color mode according to the scene.

**Home Assistant Version**
2021.11.4

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
I followed the instructions in the link, but there was nothing in the log

**Additional context**
Tried it with many different brand/model Tuya lights

**Comment by jonm802** [comment]
This behaviour is the same when you use automation to set specific lighting levels/colour

you cant set the warmth/brightness and colour the same time

the short work around is to manually edit your scenes yaml file, remove what you don't need

if your setting a colour mode remove the brightness/colour temp

**Comment by quantumfrost** [comment]
> if your setting a colour mode remove the brightness/colour temp

Unfortunately, for many of my scenes, I need to set both color and brightness. So the only option is to turn my scenes into scripts, with two service calls for each light. Plus, you need a delay of at least 1 s between setting the color and brightness, otherwise it doesn't work or turns back to white mode. That isn't as maintainable or easy to edit as a scene.

**Comment by chiments** [comment]
Same for me, exactly this behavior - tried multiple combinations in yaml and such.  

I have also noticed that this also happens when trying to set the color manually by a button. Will work when already set to a color, but when the bulb is white and vice versa. 

## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | America/Winnipeg

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4178
Installed Version | 1.18.0
Stage | running
Available Repositories | 974
Installed Repositories | 23

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 30.8 GB
disk_used | 7.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), Visual Studio Code (3.6.2), TasmoAdmin (0.16.0), SSH & Web Terminal (9.1.1), CEC Scanner (3.0), motionEye (0.16.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 10
views | 7
mode | storage

</details>

**Comment by quantumfrost** [comment]
I just decided to get rid of this buggy mess of an integration and go with Local Tuya. It responds faster and also allows you to set color and brightness simultaneously.

**Comment by rDini** [comment]
I just found out.
You need to remove : 
```
      brightness: 255
```
Example:
```
  name: Red
  entities:
    light.escri_1:
    #  supported_color_modes:
    #  - brightness
    #  - color_temp
    #  - hs
   #   - onoff
   #   brightness: 255
      color_name: red
      friendly_name: escri 1
      state: 'on'
```
Most of the code are "default" so no need to keep them.

The following examples will works 
```
    light.corre_3:
      transition: 3
      color_mode: hs
      hs_color:
      - 360
      - 100
      friendly_name: corre 3
      state: 'on'
```
```
    light.corre_3:
      color_name: red
      friendly_name: corre 3
      state: 'on'
```
For brightness I'm making a separated scene:
```
    light.corre_3:
      brightness: 60
      friendly_name: corre 3
      state: 'on'
```

**Comment by ebmarquez** [comment]
@rDini  thanks for the snips, this helped me with my lights.  I updated my scene.yaml and I removed the supported_color_modes section and removed brightness. I also saw some people updated supported_features to 63.  Once I did all three and restarted HA, the lights worked as expected.
```yaml
# Define an entity for a Tuya smart light bulb
- id: '1661801893318'
  name: After Hours Desk Lamp
  entities:
    # Define the entity ID for the light bulb
    light.desk_color_lights:
      # Define the minimum and maximum color temperature values
      min_mireds: 153
      max_mireds: 500
      # Set the color mode to "hs"
      color_mode: hs
      # Define the hue and saturation values
      hs_color:
      - 360
      - 100
      # Define the red, green, and blue values
      rgb_color:
      - 255
      - 0
      - 0
      # Define the x and y values
      xy_color:
      - 0.701
      - 0.299
      # Set a friendly name for the light bulb
      friendly_name: Desk Color Lights
      # Set the supported features to all
      supported_features: 63
      # Set the state to "on"
      state: 'on'
  # Define any additional metadata for the entity
  metadata: {}
  # Set the icon to use for the entity in the Home Assistant UI
  icon: mdi:desk-lamp
```
