### ISSUE TITLE
Tuya - Error While Get MQTT Config

### ISSUE THREAD

**Issue by CC91300** [tuya/tuya-home-assistant#741]
The problem
Receiving this error in the Core log:

[2021-12-14 07:02:53,221] [tuya-openmq] error while get mqtt config
2021-12-14 07:02:53 ERROR (Thread-9) [tuya_iot] error while get mqtt config

Note: All Tuya devices are working correctly.

What version of Home Assistant Core has the issue?
core-2021.12.1

What was the last working version of Home Assistant Core?
core-2021.12.0

What type of installation are you running?
Home Assistant OS

Integration causing the issue
Tuya

Link to integration documentation on our website
https://www.home-assistant.io/integrations/tuya/

Example YAML snippet
N/A
Anything in the logs that might be useful for us?
[2021-12-14 07:02:53,221] [tuya-openmq] error while get mqtt config
2021-12-14 07:02:53 ERROR (Thread-9) [tuya_iot] error while get mqtt config

**Comment by DIMMonchik** [comment]
The same error appeared after the update to version 2021.12.3

**Comment by MaxK99** [comment]
This is a recurring problem and/or related to:

https://github.com/tuya/tuya-home-assistant/issues/731
https://github.com/tuya/tuya-home-assistant/issues/733
https://github.com/tuya/tuya-home-assistant/issues/740

https://github.com/home-assistant/core/issues/59643
https://github.com/home-assistant/core/issues/59689
https://github.com/home-assistant/core/issues/59872
https://github.com/home-assistant/core/issues/59874
https://github.com/home-assistant/core/issues/59911
https://github.com/home-assistant/core/issues/61820

**Comment by dgthomson** [comment]
A workaround as posted elsewhere:

In **configuration.yaml** add (or confirm it contains:

```
system_log:
  fire_event: true
```

In **automations.yaml**, add:

```
- id: "TuyaIOT"
  alias: "TuyaIOT Restart"
  trigger:
  - platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
      name: tuya_iot
  condition:
  - condition: template
    value_template: >-
      {{ "error while get mqtt config" in trigger.event.data.message[0] }}
  action:
  - service: homeassistant.reload_config_entry
    data:
      entity_id:
        - switch.living_room_lamp
```

**Important!** Change `switch.living_room_lamp` to the id of one of your system's own Tuya entities.

Works like a charm by resetting Tuya when `error while get mqtt config` occurs.
