### ISSUE TITLE
Tuya integration does not give status anymore after overnight

### ISSUE THREAD

**Issue by bartplessers** [tuya/tuya-home-assistant#844]
**Description**
I use home assistant with tuya integration.

Everything works well, but I noticed that in the morning, I can turn ON my light, but I can’t turn it OFF anymore.
This is because my automation TOGGLE's the light:

```
# -----------------------------------------------
- id: '0x00158d000428fb20_action_single_right'
  alias: (S09) switch action single_right
  initial_state: true
  trigger:
  - entity_id: sensor.my_n01_p03_switch_s09_wandschakelaar_action
    platform: state
    to: single_right
  action:
  - entity_id: light.group_n01_p03_wastafel
    service: light.toggle
# -----------------------------------------------
```
and apparently the new STATUS of the light is not recognized.
So what happens:

- light is off
- toggle command turns it on
- but status (in hass) seems to remain off

If I push my switch again,
- light is on (but hass thinks its off)
- hass sends command to turn it on (but it is already on)

If I just reload my Tuya automations, things works perfect for “a while”. Don’t know for witch period, but it I notice that in the morning it has above behavior

Does anybody has the same experience?
Resolution?

kind regards,
Bart

**Expected behavior**

The status of Tuya devices is correctly displayed in HASS

**Diagnostics for integrations and devices**

see
[config_entry-tuya-179341e4676b8c0e6284065b58a431f9.json.txt](https://github.com/tuya/tuya-home-assistant/files/9536583/config_entry-tuya-179341e4676b8c0e6284065b58a431f9.json.txt)

**Home Assistant Version**
Home Assistant 2022.9.1

**Device info (please complete the following information, which can be found in [log]
        "name": "Badkamer - Wastafel ",
        "model": "ST2776G Wifi+\u84dd\u7259BLE",
        "category": "dj",
        "product_id": "0xmtemznyuvx7iim",
        "product_name": "Up/Down Light RGB+CCT",
        "online": true,
        "sub": false,

(for more details, see attached file)
